added detailed view of recipe
klillenb/mobile-application-dev pull request #6
Opened 2023-05-12 08:44 UTC by Reydan7

2023-05-12 20:59 UTC, klillenb requested changes
mõned kysimused tekkisid, also Update from main ja konfliktid vaja lahendada sest uus dto struktuur on - dbs tegin kõrvale uue pisema kollektsiooni mida kasutame serveril ja seal salvestame pilte base64 formaadis pilte

2023-05-12 20:59 UTC, klillenb commented on final/app/build.gradle
> +    }
need teevad sama asja - https://stackoverflow.com/questions/71972954/whats-the-difference-between-viewbinding-enabled-true-and-buildfeatures-viewbin

2023-05-12 20:59 UTC, klillenb commented on final/app/src/main/java/com/example/mobileapp/dto/RecipeDto.kt
> +        parcel.createStringArrayList()
kas see peab nii olema? Väga palju kordust

2023-05-13 19:35 UTC, Reydan7 commented on final/app/src/main/java/com/example/mobileapp/dto/RecipeDto.kt
> +        parcel.createStringArrayList()
jah, see parce-ib uhelt objektilt teisele: https://medium.com/@hgarg701/parcelable-in-android-using-kotlin-pass-object-from-one-activity-to-another-c34801d7ff03

2023-05-13 20:51 UTC, Reydan7 commented on final/app/build.gradle
> +    }
tehtud

2023-05-14 17:11 UTC, klillenb requested changes
tagasi navigeerimine tööle saab siis mergeks ära

2023-05-14 17:11 UTC, klillenb commented on final/app/src/main/java/com/example/mobileapp/dto/RecipeDto.kt
> +    val description: String?,
Retsepti lisamise funktsioon on nii seadistatud, et ei tekiks olukorda kus saaks üles laadida kui mingi väli tühi on, seega siin nullable tüübide määramine ebavajalik. GET päringud samamoodi tagastavad kõik väljad (v.a selle esimese retsepti pilt, mis juba on nullable). Või see on pigem mõne sinu lisatud funktsionaalsuse jaoks tarvis?

2023-05-14 17:11 UTC, klillenb commented on final/app/src/main/java/com/example/mobileapp/repository/RecipeRepository.kt
Kas jätta muudatused sõltub data classi lahendusest, ehk et kui sul on vaja et oleks nullable ss timm, kui ei siis let'id ebavajalikud

2023-05-14 17:11 UTC, klillenb commented on final/app/src/main/java/com/example/mobileapp/ui/recipes/RecipeDetailFragment.kt
Vb üks lahendus navigeerimise probleemi lahendamiseks oleks luua tagasi nupp, millel oleks hardcoded navigate to retseptiloendi kuvale? Kiire googeldamine mingit pädevat vastust ei anna tho

2023-05-14 17:11 UTC, klillenb commented on final/app/src/main/java/com/example/mobileapp/ui/recipes/RecipesFragment.kt
> +        }*/
kui seda osa vaja pole, siis oleks see täiesti eemaldada

2023-05-14 17:11 UTC, klillenb commented on final/app/src/main/java/com/example/mobileapp/ui/recipes/RecipesFragment.kt
>                  //Toast.makeText(activity, "klikkisid kogu elemendile", Toast.LENGTH_SHORT).show()
samamoodi kasutamata osi pole mõtet sisse jätta

2023-05-14 17:11 UTC, klillenb commented on final/app/src/main/java/com/example/mobileapp/ui/recipes/RecipesFragment.kt
> +            .addToBackStack(null)
huvitav kas äkki sellepärast ei saagi tagasi navigeerida? Või ei saa navigeerida tagasi, sest vastav funktsioon pole implementeeritud? https://stackoverflow.com/questions/10863572/programmatically-go-back-to-the-previous-fragment-in-the-backstack
nt see kuskile lisada -> getFragmentManager().popBackStackImmediate();

2023-05-15 07:29 UTC, merged